name: UwUCore
version: '${project.version}'
main: me.aroze.uwucore.UwUCore
api-version: 1.19
authors: [ Aroze ]
description: um
website: aroze.me
commands:
  gamemode:
    aliases: [ gm, gms, gmc, gma, gmsp, gmspec, gm0, gm1, gm2, gm3 ]
  heal:
    aliases: [ sheal, softheal]
  kittycannon:
    aliases: [ kittygun ]
